name: eaton-scripps-CO
channels:
  - conda-forge
  - defaults  
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pandas
  - netcdf4
  - cartopy
  - cmocean
  - seaborn
  - cmocean
  - ipykernel
  - pyyaml

  - pip:
      - dask
      - xarray==2022.11.0



